### ISSUE TITLE
Cannot read property 'models' of undefined on startup

### ISSUE THREAD

**Issue by douglasg14b** [douglasg14b/TalkDesk-Real-Time-Pause-States#6]
Occurs after: `angular.bootstrap($('#userStatuses').parent(), ['statusesApp']);`

Seems to occur when TalkDesk resources are not fully instantiated before angular is bootstrapped and tries to reference model data.

Error:

> Cannot read property 'models' of undefined
>     at new eval (eval at <anonymous> (eval at <anonymous> (unknown source)), <anonymous>:397:49)
>     at Object.invoke (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:41:295)
>     at T.instance (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:86:444)
>     at u (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:65:338)
>     at g (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:58:136)
>     at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:57:279
>     at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:21:88
>     at m.$eval (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:141:47)
>     at m.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:141:280)
>     at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js:21:44

**Comment by douglasg14b** [comment]
Fixed by ensuring agents is defined before bootstrapping angular.
